config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 get '/meet' => 'breakwater#meet_the_team'
 get '/timeline' => 'breakwater#timeline'
 get '/about' => 'breakwater#about'
 get '/news' => 'breakwater#news'
 root 'breakwater#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breakwater_controller.rb
class BreakwaterController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/section_nav_helper.rb
module SectionNavHelper
  def find_active_section(active_section, current_section)
    active_section.upcase == current_section.upcase ? "active" : ""
  end
end

app/views/breakwater/about.html.erb
<div class='about'>
  <h4> What is Breakwater Chicago? </h4> 

  Breakwater Chicago is a luxurious destination vessel being designed by Breakwater Chicago LLC. It will 

  be the first floating entertainment venue of its kind anywhere in the world, providing guests with the 

  amenities of a five-star hotel while simultaneously offering a sense of your very own mega-yacht.

  <hr /><h4> What is the purpose of your business? </h4>

  Breakwater Chicago’s mission is to create an entertainment venue utterly unique to Chicago: a national 

  and international attraction bringing visitors to experience a world-class city in an unprecedented way, 

  by enjoying an extraordinary location that is both luxurious and truly at harmony with its environment.

  <hr /><h4> Where will this be located? </h4>

  The venue will operate as a floating vessel on Lake Michigan just off of Chicago’s beautiful shoreline, 

  north and east of Navy Pier in a deserted anchorage zone that Breakwater Chicago will transform into 

  the premier boating and tourist destination for Chicago during summer months.

  <hr /><h4> How do people get out to the vessel? </h4>

  There are several companies that currently operate water taxi services along the Chicago River and Lake 

  Michigan. After speaking with ownership of two such companies, we have decided to outsource this 

  service on a contractual basis to existing entities. Water taxis will be provided free of charge to guests of 

  Breakwater Chicago. Private boaters can also join us by using the attached floating-pier for a docking fee 

  or our boat-valet service for temporary local mooring in Monroe Harbor.

  <hr /><h4> How much will it cost to build? </h4>

  Based on estimates provided by architectural and naval design firms, general contractors, shipyards, and 

  food and beverage operators we are budgeting for a $23mm total project cost. This figure includes all 

  design, permitting, construction, marketing, and legal expenses, as well as allowances for contingencies 

  and pre-launch working capital. While construction costs are higher than land-based hospitality 

  projects, our company will then own the platform and not be required to pay rental rates in the 

  competitive Chicago real estate market. This will allow Breakwater to generate stronger than average 

  operating cashflows by avoiding one of the highest expenses on a renting venue’s P&L.

  <hr /><h4> How much space will you have to operate? </h4>

  As it currently stands in our design, the vessel for Breakwater will be 100’ wide and 300’ long, creating 

  of area on the main deck. There is also 10,000 ft2

  30,000 ft2

  main lounge space, and another 10,000 square feet on top of that for a sun deck. 50,000 ft2

  space, less 10,000 ft2

  We have also designed 12’ of height between the deck and the hull, meaning that another 30,000 ft2

  be available below-deck for kitchens, mechanical spaces, bathrooms, changing facilities, and storage.

  of pool, results in approximately 40,000 ft2

  on a second level, which will house the 

  of usable hard surfaces above deck. 

  of total 

  will
</div>

app/views/breakwater/index.html.erb
<ul class="carousel" data-orbit data-options="animation_speed:500; animation:fade; pause_on_hover:false; slide_number:false">
  <li>
    <%= image_tag 'onboard.png', alt: 'slide 3', class:'carousel-image' %>
  </li>
  <li>
    <%= image_tag 'profile_night.png', alt: 'slide 2', class:'carousel-image' %>
    <div class="orbit-caption">
      Caption.
    </div>
  </li>
  <li>
    <%= image_tag 'bay.png', alt: 'slide 1', class: 'carousel-image' %>
  </li>
</ul>

<div class='row'>
  <div class='large-6 columns'>
    <p class='quote'>“The Lakefront by right belongs to the people.  Not a foot of its shores should be appropriated to the exclusion of the people.” - Daniel Burnham</p>
  </div>
  <div class='large-6 columns'>
    <%= image_tag 'on_deck.png' %>
  </div>

</div>

app/views/breakwater/meet_the_team.html.erb
<div class="meet">
  <div class = "row">
    <div class="small-2 columns">
      <%=image_tag "beau_headshot.png" %>
    </div>
    <div class = "small-10 columns">
      <p>o deduco sto textilis decipio. Laboriosam coepi despecto vapulus vulgivagus desolo videlicet abstergo. Canto cursim approbo voluntarius curatio thymum. Bos ulterius tribuo tenetur condico. Speciosus voluptas sint. Blanditiis arceo crebro vergo conspergo suasor
ia. Crebro uter earum acsi decerno candidus at ut. Culpo talus tener. Xiphias alioqui minus ultio taedium despirmatio. Thermae tremo oc
caecati. Cruentus taceo volup vomito autem vesica desidero allatus. </p>
    </div>
  </div>
  <hr  />
  <div class = "row">
    <div class="small-2 columns">
      <%=image_tag "ashvin_headshot.png" %>
    </div>
    <div class = "small-10 columns">
      <p>o deduco sto textilis decipio. Laboriosam coepi despecto vapulus vulgivagus desolo videlicet abstergo. Canto cursim approbo voluntarius curatio thymum. Bos ulterius tribuo tenetur condico. Speciosus voluptas sint. Blanditiis arceo crebro vergo conspergo suasor
ia. Crebro uter earum acsi decerno candidus at ut. Culpo talus tener. Xiphias alioqui minus ultio taedium despirmatio. Thermae tremo oc
caecati. Cruentus taceo volup vomito autem vesica desidero allatus. </p>
    </div>
  </div>
  <hr />
  <div class = "row">
    <div class="small-2 columns">
      <%=image_tag "elizabeth_headshot.png" %>
    </div>
    <div class = "small-10 columns">
      <p>o deduco sto textilis decipio. Laboriosam coepi despecto vapulus vulgivagus desolo videlicet abstergo. Canto cursim approbo voluntarius curatio thymum. Bos ulterius tribuo tenetur condico. Speciosus voluptas sint. Blanditiis arceo crebro vergo conspergo suasor
ia. Crebro uter earum acsi decerno candidus at ut. Culpo talus tener. Xiphias alioqui minus ultio taedium despirmatio. Thermae tremo oc
caecati. Cruentus taceo volup vomito autem vesica desidero allatus. </p>
    </div>
  </div>

</div>

app/views/breakwater/news.html.erb
<div class="news">
  <div class = "row event">
    <div class="small-2 columns">
      <%=image_tag "event3.jpeg" %>
    </div>
    <div class = "small-10 columns">
      <h4> Skotch Tasting @ The Mast Head </h4><h6><em> Oct. 20th, 2016 </em> </h6>
      <p>o deduco sto textilis decipio. Laboriosam coepi despecto vapulus vulgivagus desolo videlicet abstergo. Canto cursim approbo voluntarius curatio thymum. Bos ulterius tribuo tenetur condico. Speciosus voluptas sint. Blanditiis arceo crebro vergo conspergo suasor
ia. Crebro uter earum acsi decerno candidus at ut. Culpo talus tener. Xiphias alioqui minus ultio taedium despirmatio. Thermae tremo oc
caecati. </p>
    </div>
  </div>
  <div class = "row event">
    <div class="small-2 columns">
      <%=image_tag "lake_skyline.jpg" %>
    </div>
    <div class = "small-10 columns">
      <h4> Free Water Taxis </h4><h6><em> Nov. 29th, 2016 </em> </h6>
      <p>o deduco sto textilis decipio. Laboriosam coepi despecto vapulus vulgivagus desolo videlicet abstergo. Canto cursim approbo voluntarius curatio thymum. Bos ulterius tribuo tenetur condico. Speciosus voluptas sint. Blanditiis arceo crebro vergo conspergo suasor
ia. Crebro uter earum acsi decerno candidus at ut. Culpo talus tener. Xiphias alioqui minus ultio taedium despirmatio. Thermae tremo oc
caecati. Cruentus taceo volup vomito autem vesica desidero allatus. </p>
    </div>
  </div>
  <div class = "row event">
    <div class="small-2 columns">
      <%=image_tag "event1.jpeg" %>
    </div>
    <div class = "small-10 columns">
      <h4> New Years Ball </h4><h6><em> Jan. 1st, 2016 </em> </h6>
      <p>o deduco sto textilis decipio. Laboriosam coepi despecto vapulus vulgivagus desolo videlicet abstergo. Canto cursim approbo voluntarius curatio thymum. Bos ulterius tribuo tenetur condico. Speciosus voluptas sint. Blanditiis arceo crebro vergo conspergo suasor
ia. Crebro uter earum acsi decerno candidus at ut. Culpo talus tener. Xiphias alioqui minus ultio taedium despirmatio. Thermae tremo oc
caecati. Cruentus taceo volup vomito autem vesica desidero allatus. </p>
    </div>
  </div>
  <div class = "row event">
    <div class="small-2 columns">
      <%=image_tag "event2.jpeg" %>
    </div>
    <div class = "small-10 columns">
      <h4> $10 off Breakfast @ Treaty of Paris </h4><h6><em> Feb. 20th, 2017 </em> </h6>
      <p>o deduco sto textilis decipio. Laboriosam coepi despecto vapulus vulgivagus desolo videlicet abstergo. Canto cursim approbo voluntarius curatio thymum. Bos ulterius tribuo tenetur condico. Speciosus voluptas sint. Blanditiis arceo crebro vergo conspergo suasor
ia. Crebro uter earum acsi decerno candidus at ut. Culpo talus tener. Xiphias alioqui minus ultio taedium despirmatio. Thermae tremo oc
caecati. Cruentus taceo volup vomito autem vesica desidero allatus. </p>
    </div>
  </div>

</div>

app/views/breakwater/timeline.html.erb
<div class="timeline">
  <h3 class="timeline-title">History of Breakwater</h3>
  <div class="slide-bg">
  </div>
  <div class="panel-container">
    <div class="slide-panel">
      <div class="time-label">2008</div>
      <h2 class="panel-title">Concept</h2>
      <div class="panel-content">Iure earum voluptate dignissimos provident quia. Quaerat fuga aut ut velit omnis eaque iure. Illum quo odio aut voluptatem quis. Quo quia labore suscipit. Occaecati neque nostrum non minima labore voluptatem.</div>
    </div>
    <div class="slide-panel">
      <div class="time-label">2009</div>
      <h2 class="panel-title">Funding</h2>
      <div class="panel-content">Blanditiis recusandae praesentium facere quo in aut voluptatem. Sed ut id debitis consequuntur. Perspiciatis est tempore quae nostrum sed. Minus odio velit illo ab quas dolore qui. Eligendi ducimus at sit sed sequi rerum qui.</div>
    </div>
    <div class="slide-panel">
      <div class="time-label">2010</div>
      <h2 class="panel-title">Approval</h2>
      <div class="panel-content">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam corporis odit eum facere voluptas. Aut distinctio nam, fugiat eius facere officiis adipisci cupiditate inventore rerum veniam cumque et dolores ex.</div>
    </div>
    <div class="slide-panel">
      <div class="time-label">2011</div>
      <h2 class="panel-title">Construction</h2>
      <div class="panel-content">Vel quia est. Quas omnis et. Facere consequatur excepturi ipsa quasi placeat. Qui in rem non et eos sed rerum. Et optio soluta quis sit voluptate. Enim officiis esse culpa in quisquam nemo nihil.</div>
    </div>
    <div class="slide-panel">
      <div class="time-label">CURRENT</div>
      <h2 class="panel-title">Built</h2>
      <div class="panel-content">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi, eligendi sunt aperiam ipsa nemo sed similique pariatur quaerat expedita velit. Nemo voluptate ducimus sunt dolores aliquid. Cum, tempore quia quas.</div>
    </div>
  </div>
  <div class="slide-nav"></div>
</div>

app/views/layouts/_about.html.erb
<%= render "layouts/section_nav", active_section:"About" %>
<div id="about">
  <div class="bg-silhouette"></div>
  <div class = "row">
    <div class = "small-9 small-centered columns">
      <p>o deduco sto textilis decipio. Laboriosam coepi despecto vapulus vulgivagus desolo videlicet abstergo. Canto cursim approbo voluntarius curatio thymum. Bos ulterius tribuo tenetur condico. Speciosus voluptas sint. Blanditiis arceo crebro vergo conspergo suasor
ia. Crebro uter earum acsi decerno candidus at ut. Culpo talus tener. Xiphias alioqui minus ultio taedium despirmatio. Thermae tremo oc
caecati. Cruentus taceo volup vomito autem vesica desidero allatus. Tabernus conventus creator clamo ut. Coniecto conor amaritudo. Aut 
carpo commemoro amplus sed. Tribuo ciminatio depono. Crinis omnis armarium acer. Tero quia porro cura. Umerus aut caecus</p>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class='row'>
<hr />
  <div class='small-4 columns'>
    Copyright &copy; 2014. All Rights Reserved
  </div>
  <div class='small-3 columns right'>
    Site by <a href="https://www.linkedin.com/profile/view?id=278619359">Daniel Schepers</a>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<% require 'pry'%>
<nav class="row">
<a href="/" class="logo-section small-3 columns"></a>
<div class="large-9 columns no-padding-right">
  <ul class="right">
    <% if !current_user %>
      <li>
        <a data-dropdown="login_form" aria-controls=login_form aria-expanded='false'>Login</a>
          <ul id="login_form" class="f-dropdown small" data-dropdown-content aria-hidden="true" tabindex="-1">
            <%= form_for(User.new, as: :user, url: session_path(:user)) do |f| %>
              <div><%= f.label :email %><br />
                <%= f.email_field :email, autofocus: true %></div>
              <div><%= f.label :password %><br />
                <%= f.password_field :password, autocomplete: "off" %></div>
                <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
              <div><%= button_tag "Log in", :class => 'btn btn-submit'%></div>
              <%= link_to "Forgot your password?", new_password_path(:user) %><br />
            <% end %>
          </ul>
      </li> &nbsp; | &nbsp;
      <li><a data-dropdown='registration_form' aria-controls='registration_form' aria-expanded='false'>Register</a>
        <ul id="registration_form" class="f-dropdown small" data-dropdown-content aria-hidden="true" tabindex="-1">
        <%= form_for(User.new, as: :user, url: registration_path(:user)) do |f| %>
          <div><%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true %></div>
          <div><%= f.label :password %> <% if @validatable %><i>(<%= @minimum_password_length %> characters minimum)</i><% end %><br />
            <%= f.password_field :password, autocomplete: "off" %></div>
          <div><%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off" %></div>
          <div><%= button_tag "Sign up", :class => 'btn btn-submit' %></div>
        <% end %>
        </ul>
      </li> &nbsp; | &nbsp;
      <% else %>
        <li><a data-dropdown='sign_out' aria-controls='sign_out' aria-expanded='false'> Welcome, <%=current_user.email %> <i class='fa fa-caret-down'></i></a>
          <ul id="sign_out" class="f-dropdown tiny" data-dropdown-content aria-hidden="true" tabindex="-1">
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li> 
          </ul>
        </li> &nbsp; | &nbsp;
      <% end %>
      <li>
      <a data-dropdown="language" aria-controls="language" aria-expanded="false">Language <i class='fa fa-caret-down'></i></a>
      <ul id="language" class="f-dropdown narrow" data-dropdown-content aria-hidden="true" tabindex="-1">
        <li><a href="#">English</a></li>
        <li><a href="#">Spanish</a></li>
        <li><a href="#">Swahili</a></li>
      </ul>
      </li>
      <li class='search'><%= search_field_tag 'search', nil, placeholder: 'Search' %></li>
    </ul>
  </div>
  </nav>

app/views/layouts/_section_nav.html.erb
<nav class = 'top-bar' data-topbar role = 'navigation'>
<ul class = 'title-area'>
  <li class = 'name'> </li>
  <li class = 'toggle-topbar menu-icon'><a href = '#'><span>Menu</span></a></li>
</ul>
<section class = 'top-bar-section'>
<ul class="content-nav">
  <li><%= link_to "Home", root_path %> </li>
  <li><%= link_to "Timeline", timeline_path %> </li>
  <li><%= link_to "Meet the Team", meet_path %> </li>
  <li><%= link_to "About Breakwater", about_path %> </li>
  <li><%= link_to "News & Events", news_path %> </li>
</ul>
 </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Breakwater Chicago</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= favicon_link_tag 'favicon.ico' %>
    <title>Breakwater Chicago</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="background">
    <div class='bg-silhouette'></div>
    <%= render 'layouts/navigation' %>
    <div class='content-pane row'>
      <%= render 'layouts/section_nav' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag "application" %> 
  </body>
</html>